# image will be published to ghcr.io/<user>/<name>
name: bluejay
# description will be included in the image's metadata
description: Where I live we have Eurasian jays and I like them. But the name bluejay sounds better and I also have a cap from those in Toronto, even though I know nothing about baseball. But this is my personal OS image ;-)

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/aflyhorse/libjpeg/repo/fedora-%OS_VERSION%/aflyhorse-libjpeg-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/rdnetto/fasd/repo/fedora-%OS_VERSION%/rdnetto-fasd-fedora-%OS_VERSION%.repo
    install:
      # from corp repos
      - starship
      - fasd
      #- mjpegtools-libs
      # foundation
      - neovim
      - zsh
      - syncthing
      - rsync
      - restic
      - pwgen
      - htop
      - task
      - fzf
      - ack
      - git
      - git-credential-libsecret
      - curl
      - moreutils
      - dos2unix
      - pipx
      - python3-pip
      - python3-virtualenvwrapper
      - xclip
      # development
      - sqlitebrowser
      - sqlite
      - java-latest-openjdk
      - maven
      - ghex
      - lftp
      - nodejs-npm
      - optipng
      - jpegoptim
      - exiv2
      - entr
      - openssl
      - cmake
      - gcc-c++
      - podman-docker
      - ansible
      - ansible-collection-ansible-posix
      - ansible-collection-community-docker
      - ansible-packaging
      - android-tools
      - gitg
      - tig
      - gnuplot
      - distrobox
      # development for pywb
      - python3.11
      - python3-cairo-devel
      # desktop
      - tmux
      - keepassxc
      - firefox
      - thunderbird
      - chromium
      - libreoffice-core
      - libreoffice-gtk4
      - langpacks-de
      - langpacks-en
      - gimp
      - qgis
      - qcad
      - simple-scan
      - ocrmypdf
      - tesseract-langpack-deu
      - tesseract-osd
      - qrencode
      - hedgewars
      - hunspell-de
      - hunspell-en
      - moon-buggy
      - musescore
      - file-roller-nautilus
      - cheese
      - dialect
      - foliate
      - calls
      - baobab
      - evince
      - evince-djvu
      - diffpdf
      - xournal
      - pdftk-java
      - calibre
      - gpsbabel
      - yubikey-manager
      - qflipper
      - yt-dlp
      - vlc
      - remmina-plugins-exec
      - remmina-plugins-rdp
      - remmina-plugins-secret
      - remmina-plugins-vnc
      - cups-pdf
      #- mozilla-openh264
      # system
      - NetworkManager-openconnect-gnome
      - NetworkManager-openvpn-gnome
      - NetworkManager-ssh-gnome
      - NetworkManager-vpnc-gnome
      # gnome setup
      - gnome-tweaks
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-user-theme
      - gnome-extensions-app
      - gnome-remote-desktop
      - gnome-browser-connector
      # texlive
      - texlive-collection-bibtexextra
      - texlive-collection-latexextra
      - texlive-collection-langgerman
      - texlive-collection-xetex
      - texlive-hyphen-english
      - texlive-pdfjam
      - texlive-collection-fontsrecommended
      - texlive-biblatex
      - texlive-insbox
      - texlive-latexpand
      - texlive-sankey
      - lilypond
      - latexmk
      - LaTeXML
    remove:
      # conflicks with podman-docker
      - docker-ce

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        # - org.mozilla.firefox
        # - org.gnome.Loupe
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
