version: 3

tasks:
  build:iso:
    desc: Build an ISO image for bluejay
    cmds:
      - bluebuild generate-iso --build-driver podman --inspect-driver podman --run-driver podman --iso-name bluejay-os-$(date +%F-%s).iso --output-dir build image ghcr.io/white-gecko/bluejay:latest
  
  build:iso:webui:
    desc: Build an ISO image for bluejay
    cmds:
      - bluebuild generate-iso --web-ui --build-driver podman --inspect-driver podman --run-driver podman --iso-name bluejay-os-webui-$(date +%F-%s).iso --output-dir build image ghcr.io/white-gecko/bluejay:latest
