version: '3'

includes:
  fix: ./task/FixTasks.yaml
  setup: ./task/SetupTasks.yaml
  user:
    taskfile: "{{.HOME}}/.local/share/bluejay/Taskfile.yaml"
    dir: "{{.HOME}}/.local/share/bluejay/"
    optional: true

tasks:
  default:
    desc: utask is just like ujust a Taskfile that contains some maintenance tasks to be executed. The available tasks are listed here
    aliases: ["help"]
    cmds:
      - utask -l
