version: '3'

includes:
  fix: ./task/FixTasks.yaml
  setup: ./task/SetupTasks.yaml
  install: ./task/InstallTasks.yaml
  user:
    taskfile: "{{.HOME}}/.local/share/bluejay/Taskfile.yaml"
    dir: "{{.HOME}}/.local/share/bluejay/"
    optional: true

tasks:
  default:
    desc: utask is just like ujust
    summary: |
      A Taskfile that contains some maintenance tasks to be executed. The available tasks are listed here.
    aliases: ["help"]
    cmds:
      - utask -l

  rebase-signed:
    desc: Rebase to the default and ostree-image-signed version
    cmds:
      - rpm-ostree rebase ostree-image-signed:docker://ghcr.io/white-gecko/bluejay:latest
