version: '3'

includes:
  fix: ./task/FixTasks.yaml
  init: ./task/InitTasks.yaml
  install: ./task/InstallTasks.yaml
  setup: ./task/SetupTasks.yaml
  set: ./task/SetTasks.yaml
  user:
    taskfile: "{{.HOME}}/.local/share/bluejay/Taskfile.yaml"
    dir: "{{.HOME}}/.local/share/bluejay/"
    optional: true

tasks:
  default:
    desc: utask is just like ujust
    summary: |
      A Taskfile that contains some maintenance tasks to be executed. The available tasks are listed here.
    aliases: ["help"]
    cmds:
      - utask -l
