version: '3'

includes:
  fix: ./task/FixTasks.yaml
  setup: ./task/SetupTasks.yaml
  install: ./task/InstallTasks.yaml
  user:
    taskfile: "{{.HOME}}/.local/share/bluejay/Taskfile.yaml"
    dir: "{{.HOME}}/.local/share/bluejay/"
    optional: true

tasks:
  default:
    desc: utask is just like ujust
    summary: |
      A Taskfile that contains some maintenance tasks to be executed. The available tasks are listed here.
    aliases: ["help"]
    cmds:
      - utask -l

  install-everything:
    cmds:
      - task: install:upkgs

  setup-everything:
    prompt: Make sure the INIT_KEEPASS_PASSWORD and INIT_KEEPASS_FILE are set
    vars:
      INIT_JSON:
        sh: kee-config --env --json -f "{{.INIT_KEEPASS_FILE}}" --password "{{.INIT_KEEPASS_PASSWORD}}"
      INIT:
        ref: "fromJson .INIT_JSON"
    cmds:
      - task: setup:secrets
      - task: setup:connections
      - task: setup:syncthing
        vars:
          SYNCTHING_REMOTE_ADDRESS:
            ref: .INIT.SYNCTHING_REMOTE_ADDRESS
          SYNCTHING_REMOTE_APIKEY:
            ref: .INIT.SYNCTHING_REMOTE_APIKEY
      - task: setup:chezmoi
      - task: setup:printers
      - task: setup:languagetool
